# Generated by Django 4.2.2 on 2023-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('job_url', models.URLField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
            ],
        ),
    ]
