# Generated by Django 4.1.8 on 2023-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('hall_ticket_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
